server.port: 8085
spring:
  application:
    name: spring-feign-play

  http:
    log-request-details: true

other-service:
  ribbon:
    listOfServers: http://localhost:${wiremock.server.port}
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 0
    retryableStatusCodes: 503, 408, 500
    OkToRetryOnAllOperations: false
#ribbon:# doesn't work
#  ReadTimeout: 1000
#  ConnectTimeout: 1000
feign:
  client.config.default:
    connectTimeout: '100'
    readTimeout: '1000'
    loggerLevel: basic
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      fallback.enabled: false
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
#          thread: # doesn't need it, because of hystrix.command.default.execution.timeout.enabled
#            timeoutInMilliseconds: 3000
#          semaphore:
#            maxConcurrentRequests: 100

      circuitBreaker:
        requestVolumeThreshold: 10
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    restart.enabled: true
  endpoints.web.exposure.include: '*'
  metrics.export.prometheus.enabled: true
  trace:
    http:
      include: requestHeaders,responseHeaders,cookieHeaders,authorizationHeader,principal,remoteAddress,sessionId,timeTaken

logging.level.org.qwertech: DEBUG
logging.level.org.springframework.web.filter: DEBUG
logging.level.ROOT: INFO