server.port: 8085
other-service:
  ribbon:
    listOfServers: http://localhost:${wiremock.server.port}
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 0
    retryableStatusCodes: 503, 408
    OkToRetryOnAllOperations: false
#feign:
#  hystrix:
#    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 5000
#            readTimeout: 5000
#      fallback:
#        isolation:
#          semaphore:
#            maxConcurrentRequests: 200
#            errorThresholdPercentage: 80
#            forceClosed: true

      circuitBreaker:
        requestVolumeThreshold: 100
