server.port: 8085
spring:
  application:
    name: spring-feign-play
other-service:
  ribbon:
    listOfServers: http://localhost:${wiremock.server.port}
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 0
    retryableStatusCodes: 503, 408, 500
    OkToRetryOnAllOperations: false
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

      circuitBreaker:
        requestVolumeThreshold: 10
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    restart.enabled: true
  endpoints.web.exposure.include: '*'
  metrics.export.prometheus.enabled: true